builtin_interfaces/Time stamp
uint8 base_to_car_heartbeat

uint8 TRACK_FLAG_NULL=0
uint8 TRACK_FLAG_RED=3
uint8 TRACK_FLAG_FULL_COURSE_YELLOW=9
uint8 TRACK_FLAG_GREEN=1
uint8 TRACK_FLAG_WAVING_GREEN=37
uint8 TRACK_FLAG_CHECKERED=4
uint8 marelli_track_flag

uint8 VEH_FLAG_NULL=0
uint8 VEH_FLAG_ORANGE=25
uint8 VEH_FLAG_YELLOW=7
uint8 VEH_FLAG_STOP=34
uint8 VEH_FLAG_BLUE=2
uint8 VEH_FLAG_BLACK=4
uint8 VEH_FLAG_PURPLE=32
uint8 VEH_FLAG_ENGINE_KILL=33
uint8 VEH_FLAG_DEFENDER=35
uint8 VEH_FLAG_ATTACKER=36
uint8 marelli_vehicle_flag

uint8 marelli_sector_flag
uint8 marelli_rc_base_sync_check
float64 marelli_rc_lte_rssi