# Dynamics Bicycle Model Parameters
model_params:
  cornering_stiffness_front: 130634.4
  cornering_stiffness_rear: 130634.4
  # mass: 761.
  mass: 801.5
  length_front: 1.54
  length_rear: 2.554
  yaw_moment_inertia: 550
  drag_coeff: 0.814

# Velocity Brackets to generate [m/s]
# feedback matrices from
# Q: [ lateral_error, lateral_error_dot, yaw_error, yaw_error_dot, v_error ]
# lateral_error : for reducing cross-track error
# lateral_error_dot : for enforcing ego vehicle inner side w.r.t. reference trajectory (during cornering)
velocity_brackets:
- velocity: 10
  q_trace: [3.8, 0.7, 0.1, 0.0, 5.0]   #3.0
  r_trace: [450., 30.]
- velocity: 15
  q_trace: [2.0, 0.6, 0.2, 0.0, 5.0]   #3.0
  r_trace: [300., 30.]
- velocity: 20
  q_trace: [2.0, 0.6, 0.2, 0.0, 5.0]  #2.6
  r_trace: [800., 30.]
- velocity: 25
  q_trace: [2.0, 0.4, 0.1, 0.0, 5.0]
  r_trace: [900., 30.]
- velocity: 30
  q_trace: [1.2, 0.2, 0.1, 0.0, 5.0]
  r_trace: [1000., 30.]
- velocity: 35
  q_trace: [1.0, 0.1, 0.1, 0.0, 6.0]
  r_trace: [1100., 40.]
- velocity: 40
  q_trace: [0.8, 0.07, 0.1, 0.0, 6.0]
  r_trace: [1300., 50.]
- velocity: 45
  q_trace: [0.6, 0.04, 0.1, 0.0, 6.0]
  r_trace: [1500., 60.]
- velocity: 50
  q_trace: [0.4, 0.01, 0.1, 0.0, 6.0]
  r_trace: [1750., 80.]
- velocity: 55
  q_trace: [0.3, 0.01, 0.1, 0.0, 6.0]
  r_trace: [1900., 90.]
- velocity: 60
  q_trace: [0.1, 0.01, 0.1, 0.0, 6.0]
  r_trace: [2100., 100.]