# Localization test message for ros2
# Author : Hyunwoo Nam @ KAIST
# Date : 2023.01.26

builtin_interfaces/Time stamp

#x,y,yaw
float64 bottom_odom_x
float64 bottom_odom_y
float64 bottom_yaw_deg

float64 top_odom_x
float64 top_odom_y
float64 top_yaw_deg

float64 lidar_odom_x
float64 lidar_odom_y
float64 lidar_yaw_deg

float64 estimated_odom_x
float64 estimated_odom_y
float64 estimated_yaw_deg

float64 gt_x
float64 gt_y
float64 gt_yaw_deg